export enum Age {
    TEENS = "TEENS",
    EARLY_TWENTIES = "EARLY_TWENTIES",
    MID_TWENTIES = "MID_TWENTIES",
    LATE_TWENTIES = "LATE_TWENTIES",
    EARLY_THIRTIES = "EARLY_THIRTIES",
    MID_THIRTIES = "MID_THIRTIES",
    LATE_THIRTIES = "LATE_THIRTIES",
    EARLY_FORTIES = "EARLY_FORTIES",
    MID_FORTIES = "MID_FORTIES",
    LATE_FORTIES = "LATE_FORTIES"
}